config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  get "/login", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"
  delete '/lists/:id', to: 'lists#destroy'

  get '/auth/facebook/callback' => 'sessions#loginbyfacebook'

  get '/task_count', to: 'tasks#task_count'
  resources :users do
    resources :lists
    resources :teams
  end

  resources :teams
  resources :lists
  resources :tasks
  resources :users

  get "/users/:id/tasks_to_complete", to: 'tasks#tasks_to_complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  belongs_to :team, required: false
  has_many :tasks
   accepts_nested_attributes_for :tasks
   accepts_nested_attributes_for :user

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  def self.tasks_to_complete
    where("completed == 0")
  end

  def task_user?(current_user)
    self.list.user == current_user
  end

  def boss?(current_user)
    current_user.position > self.list.user.position
  end

  def self.task_count
    all.count
  end


end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user, required: false
  has_many :users
  has_many :lists
  has_many :tasks, through: :lists


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :team, required: false
  has_many :teams
  has_many :users, through: :teams
  has_many :lists
  has_many :tasks, through: :lists

  validates :email, uniqueness: true
  validates :name, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :require_logged_in, except: [:new, :create, :home, :loginbyfacebook]

  def logged_in?
    !!current_user
  end

  private
    def require_logged_in
      redirect_to root_path unless logged_in?
    end

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController


  def new
    @list = List.new
    @user_id = params[:user_id]
  end

  def create
    @list = List.new(list_params)
    if params[:new_user_num].empty?
      @list.user_id = session[:user_id]
    end
    @list.user_id = params[:new_user_num]
    @list.tasks.collect do |t|
      if t.name == ""
        t.destroy
      end
    end
    if @list.valid?
      @list.save
      redirect_to user_list_path(current_user, @list)
    else
      render :new
    end
  end

  def update
    @list = List.find_by(id: params[:real_id])
    if params[:user_id] === @list.user_id.to_s
      @task = Task.new
      @task.name = list_params[:tasks_attributes][:"0"][:name]
      @task.list_id = @list.id
      @task.save
      respond_to do |format|
          format.json {render :json => @list}
          format.html {render 'show.html.erb'}
      end
    else
      redirect_to root_path
    end
  end

  def index
    if params[:user_id]
      @lists = User.find(params[:user_id]).lists
      respond_to do |format|
          format.json {render :json => @lists}
          format.html {render 'index.html.erb'}
        end
    else
      @lists = List.all
    end
  end

  def show
    @list = List.find_by(id: params[:id])
    if params[:currentTarget] === "next"
      @nextList = List.where("user_id = ?", @list.user_id).where("id > ?", @list.id).first
      respond_to do |format|
          format.json {render :json => @nextList}
          format.html {render 'show.html.erb'}
      end
    elsif params[:currentTarget] === "previous"
      @previousList = List.where("user_id = ?", @list.user_id).where("id < ?", @list.id).last
      respond_to do |format|
          format.json {render :json => @previousList}
          format.html {render 'show.html.erb'}
      end
    else
      respond_to do |format|
          format.json {render :json => @list}
          format.html {render 'show.html.erb'}
      end
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to user_path(current_user)
  end

  private

    def list_params
      params.require(:list).permit(:name, task_ids:[], tasks_attributes: [:name])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def new
    @user = User.new
    @users = User.all
  end

  def create
    @user = User.find_by(name: params[:user][:name])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Hi"
    else
      redirect_to login_path
    end
  end

  def loginbyfacebook
    @user = User.find_by(email: auth['info']['email']) do |u|
      u.uid = auth['uid']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
    end
    session[:user_id] = @user.id
    render '/users/show'
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def update
    task = Task.find_by(id: params[:id])
    if task.boss?(current_user) || task.task_user?(current_user)
      task.completed = params[:task][:completed]
      task.save
    else
      redirect_to user_lists_path(current_user)
    end
  end

  def tasks_to_complete
    all_uncompleted_tasks = Task.tasks_to_complete
    @tasks = []
    all_uncompleted_tasks.each do |task|
      if current_user.list_ids.include?(task.list_id)
        @tasks << task
      end
    end
  end

  def task_count
    @tasks = Task.task_count
  end

  def create
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

  def show
    @team = Team.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def home
  end

  def new
    @user = User.new
  end

  def show
   @user = current_user
  end

  def create
  @user = User.new(user_params)
   if !params[:new_team_name].empty?
     @team = Team.create(name: params[:new_team_name])
     @user.team = @team
   end
   respond_to do |format|
     if @user.save
       session[:user_id] = @user.id
       format.html { redirect_to user_path(@user) }
     else
       format.html { render :new }
     end
   end
  end

  private
   def set_user
     @user = User.find(params[:id])
   end

   def user_params
     params.require(:user).permit( :name, :password, :email, :position, :team_id, :new_team_name)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <ul>
      <% if current_user %>
        <li><%= link_to " #{current_user.name}'s Homepage", user_path(current_user) %></li>
        <li><%= link_to " #{current_user.team.name} Team's Homepage", user_team_path(current_user, current_user.team) %></li>
        <li><%= link_to "Your Lists", user_lists_path(current_user) %></li>
        <li><%= link_to "Log Out", signout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log In", login_path, class: "btn btn-primary" %></li>
        <li><%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %></li>
        <li><%= link_to('Log in with Facebook!', '/auth/facebook') %></li>
      <% end %>
    </ul>


    <%= yield %>

  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>

<% @lists.each do |list| %>
<%= link_to list.name, user_list_path(current_user, list), class: "lister" %> <br>
<% end %>

<br> <br>
<%= link_to "View all Uncompleted Tasks", "/users/#{current_user.id}/tasks_to_complete" %>

app/views/lists/new.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>

      <ul>
        <% @list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<h2>Create a list!</h2>

<%= form_for(@list) do |f| %>

  <%= hidden_field_tag :new_user_num, "#{@user_id}" %>

  <%= f.label :name, "List Name" %>
  <%= f.text_field :name %> <br><br>

  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>
  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>
  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>
  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>
  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>
  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>
  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>
  <%= f.fields_for :tasks, @list.tasks.build do |tasks| %>
    <%= tasks.text_field :name %>
  <% end %> <br>

  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div id="lists">
  <h2><%= @list.name %> </h2>
   <% @list.tasks.each do |task| %>
  <%= form_for(task) do |f| %>
      <%= f.label :name do %>
        <%= f.check_box :completed %>
        <%= task.name %>
        <%= f.submit %>
      <% end %>
    <% end %>
  <% end %>
   <% if current_user.position > @list.user.position %>
    <%= link_to 'Delete', "/lists/#{@list.id}", method: :delete%>
  <% end %>
  <%= form_for(@list) do |f| %>
    <form class="edit_list" id="new_task_submit" action="/lists/<%=@list.id%>" accept-charset="UTF-8" method="post">
      <input type="hidden" name="new_user_num" id="new_user_num" value="<%=@list.user_id%>">
      <input type="hidden" name="real_id" value="<%=@list.id%>">
      <input type="text" name="list[tasks_attributes][0][name]" id="list_tasks_attributes_0_name">
      <input type="submit" name="commit" value="Update List" data-disable-with="Update List"  class="new_task_submit">
    </form>
  <% end %>

  <div id="list_navigation">
    <%= link_to "previous", "/users/#{@list.user_id}/lists/#{@list.id}", class: "previous" %>     <%= link_to "next", "/users/#{@list.user_id}/lists/#{@list.id}", class: "next" %>
  </div>
</div>


<script id="list-template" type="text/x-handlebars-template">
  <div id="lists">
    <h2>{{name}} </h2>
      {{#each tasks}}
      <form class="edit_task" id="edit_task_{{id}}" action="/tasks/{{id}}" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="patch"><input type="hidden" name="authenticity_token" value="3nrRL2Z2ZvyuPdKTpmID/Yg2CIVw5oIALoGTzi7DIZA34yXx2hjdfA+j7Zeq22Dow2/UJvfXmuOLWe+K5FPxPQ==">
        <label for="task_name">
          <input name="task[completed]" type="hidden" value="0"><input type="checkbox" value="1" {{#if completed}} checked="checked" {{/if}} name="task[completed]" id="task_completed">
          {{name}}
          <input type="submit" name="commit" value="Update Task" data-disable-with="Update Task">
        </label>
      </form>
      {{/each}}
      <form class="edit_list" id="new_task_submit" action="/lists/{{id}}" accept-charset="UTF-8" method="post">
        <input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="_method" value="patch">
        <input type="hidden" name="real_id" value="{{id}}">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="hidden" name="new_user_num" id="new_user_num" value="{{user_id}}">
        <input type="text" name="list[tasks_attributes][0][name]" id="list_tasks_attributes_0_name">
        <input type="submit" name="commit" value="Update List" data-disable-with="Update List"  class="new_task_submit">
      </form>
      <div id="list_navigation">
       <a class="previous" href="/users/{{user_id}}/lists/{{id}}">previous</a>     <a class="next" href="/users/{{user_id}}/lists/{{id}}">next</a>
      </div>
  </div>
</script>

app/views/tasks/task_count.html.erb
There are <%= @tasks %> tasks total

app/views/tasks/tasks_to_complete.html.erb
<% @tasks.each do |task| %>
<%= form_for(task) do |f| %>
    <%= f.label :name do %>
      <%= f.check_box :completed %>
      <%= task.name %>
      <%= f.submit %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
      </h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name%>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email%>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password%>
  <br>
  <%= f.label :position %>
  <%= f.number_field :position%>
  <br>
  <%= f.label :team %>
  <%= f.collection_select :team_id, Team.order(:name),:id,:name, include_blank: true %>
or Create New
  <%= label_tag :new_team_name, "Team" %>
  <%= text_field_tag :new_team_name %>
  <br>
  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/users/home.html.erb
<h1>Welcome to Team Task Manager!</h1>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome! <%= @user.name %> </h1>

<ul>
  <li>Position: <%= @user.position %></li>
  <li>Team <%= @user.team.name %></li>
  <li><%= link_to "Lists", user_lists_path(@user), id: "lists_link" %> </li>
    <div id="listed_lists">
      <ol>
      </ol>
    </div>

</ul>

<p>  <%= link_to "Create New List", new_user_list_path(@user) %></p>


<script id="lists-template" type="text/x-handlebars-template">
  <div id="listed_lists">
    <ol>
      {{#each lists}}
      <li>
        <a href="/users/{{user_id}}/lists/{{id}}">{{name}}</a>
      </li>
      {{/each}}
    </ol>
      <button id="alpha" href="/users/{{user_id}}/lists" type="submit">Alphabatize</button>
</script>